name: Deploy

on:
  push:
    branches: [main, develop]

jobs:
  setEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Set Environment
        run: |
          echo ${{ github.ref }}
          environment=${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          if [ $environment == 'prod' ]; then
            port='3101'
          else
            port='3100'
          fi
          dockerName='authqdsj'
          echo "environment=${environment}" >> data.env
          echo "port=${port}" >> data.env
          echo "dockerName=${dockerName}" >> data.env
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-env
          path: data.env

  deploy:
    runs-on: ubuntu-latest
    needs: setEnv # 指定依赖关系
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: data-env

      - name: Load variables
        run: |
          source data.env
          echo ${environment}
          echo ${port}
          echo ${dockerName}
      - name: Set up variables
        id: vars
        run: |
          date=$(date +'%Y%m%d_%H%M%S')
          version=$(node -p "require('./package.json').version")
          tag='${environment}-${ version }-${ date }'
          echo ${tag}
          echo "tag=${tag}" >> $GITHUB_ENV
      - name: Print tag
        run: |
          echo "tag=${tag}"
          echo ${environment}
          echo ${port}
          echo ${dockerName}
      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 构建并推送 Docker 镜像
      - name: Build and push
        env:
          DOCKER_TAG: ${{ steps.vars.outputs.tag }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zenoschen/authqdsj:${tag}

      # 通过 SSH 在服务器上部署
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull zenoschen/${dockerName}:${tag}
            docker stop ${dockerName} || true
            docker rm ${dockerName} || true
            docker run -d --name ${dockerName} \
              -p ${port}:${port} \
              -e DB_HOST=${{ secrets.SERVER_HOST }} \
              -e DB_USERNAME=${{ secrets.SERVER_SQL_TODOLIST_NAME }} \
              -e DB_PASSWORD=${{ secrets.SERVER_SQL_TODOLIST_KEY }} \
              -e DB_PORT=${{ secrets.SERVER_SQL_PORT }} \
              -e DB_DATABASE=authqdsj \
              zenoschen/${dockerName}:${tag}
