name: Common Steps

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      port:
        required: true
        type: string
      docker_name:
        required: true
        type: string
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Set up variables
        id: vars
        run: |
          date=$(date +'%Y%m%d_%H%M%S')
          version=$(node -p "require('./package.json').version")
          echo "tag=${{ inputs.branch }}-${ version }-${ date }" >> $GITHUB_OUTPUT

      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 构建并推送 Docker 镜像
      - name: Build and push
        env:
          DOCKER_TAG: ${{ steps.vars.outputs.tag }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zenoschen/authqdsj:${{ env.DOCKER_TAG }}

      # 通过 SSH 在服务器上部署
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull zenoschen/${{ inputs.docker_name }}:${{ steps.vars.outputs.tag }}
            docker stop ${{ inputs.docker_name }} || true
            docker rm ${{ inputs.docker_name }} || true
            docker run -d --name ${{ inputs.docker_name }} \
              -p ${{ inputs.port }}:${{ inputs.port }} \
              -e DB_HOST=${{ secrets.SERVER_HOST }} \
              -e DB_USERNAME=${{ secrets.SERVER_SQL_TODOLIST_NAME }} \
              -e DB_PASSWORD=${{ secrets.SERVER_SQL_TODOLIST_KEY }} \
              -e DB_PORT=${{ secrets.SERVER_SQL_PORT }} \
              -e DB_DATABASE=authqdsj \
              zenoschen/${{ inputs.docker_name }}:${{ steps.vars.outputs.tag }}
