on:
  push:
    branches: [develop]
jobs:
  develop:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Start deploy
        uses: ./.github/actions
        with:
          branch: develop
          port: '3100'
          docker_name: 'authqdsj'
