name: Main

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set Main Branch variables
        run: |
          echo "qdsj-branch=main" >> data.env
          echo "qdsj-port=3101" >> data.env
          echo "qdsj-docker-name=authqdsj" >> data.env
          cat data.env
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dataEnv
          path: data.env
