on:
  push:
    branches: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Start deploy
        uses: ./.github/workflows/deploy.yml
        with:
          branch: main
          port: '3101'
          docker_name: 'authqdsj'
