name: Main

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set Main Branch variables
        run: |
          echo "qdsjBranch=main" >> data.env
          echo "qdsjPort=3101" >> data.env
          echo "qdsjDockerName=authqdsj" >> data.env
          cat data.env
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dataEnv
          path: data.env
